name: c_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取仓库源代码
      - name: Checkout the code
        uses: actions/checkout@v4.2.2
          
      # 读取项目地址
      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat c-project-to-build)" >> $GITHUB_OUTPUT
        
      # 拉取项目源码到虚拟环境
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project
        
      # 构建
      - name: Build the files
        working-directory: ./project
        run: |
          sudo apt install libnfc
          autoreconf -is
          ./configure
          make && sudo make install

      # 打包上传生成的 exe 到的网页端
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: my-build-files
          path: ./*
